import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { ThemeProvider, createTheme, Box } from "@mui/material";
import customTheme from "../styles/theme";
import Map from "../components/Map";
import useMediaQuery from "@mui/material/useMediaQuery";

const Home: NextPage = () => {
  const theme = createTheme(customTheme);
  const matches = useMediaQuery("(min-width:400px)");

  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Navbar />
        <div className={matches ? styles.desktop : styles.mobile}>
          <Map />
        </div>
      </ThemeProvider>
    </div>
  );
};

export default Home;
